[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
defi_escrow = "BD7NH19PHYwgpDDcAY5JAgNWByeVDYwHbTV5vpZv8VYJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet" # <--- This is the final, correct setting
wallet = "/home/abhi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
